# Use Node.js image
FROM node:22

# Set working directory
WORKDIR /app

# Copy package.json and install dependencies
COPY package.json yarn-lock.json ./
RUN yarn install --frozen-lockfile

# Copy rest of the app
COPY . .

# Build the Next.js app
RUN yarn build

# Expose the port
EXPOSE 3000

# Start Next.js in production mode
CMD ["yarn", "start"]
