# Use Node.js image
FROM node:22

# Set working directory
WORKDIR /app

# Copy package.json and install dependencies with Yarn
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

# Copy rest of the app
COPY . .

# Expose the port
EXPOSE 3001

# Start the NestJS application
CMD ["yarn", "start"]
